export { PageTitle } from './PageTitle'
export type { PageTitleProps } from './PageTitle'
export { Footer } from './Footer'
export type { FooterProps } from './Footer'
export { DesktopNav } from './DesktopNav'
export { NavLink } from './NavLink'
export { PersonalInformation } from './PersonalInformation'
export { MobileNav } from './MobileNav'
export { SocialLinks } from './SocialLinks'
export { Greeting } from './Greeting'
export { Avatar } from './Avatar'